--MARINA PAJVANCIC
--103340660

--RELATIONAL SCHEMA

--SUBJECT(SUBJCODE, DESCRIPTION)
--PRIMARY KEY (SUBJCODE)

--TEACHER (STAFFID, SURNAME, GIVENNAME)
--PRIMARY KEY (STAFFID)

--STUDENT(STUDENTID, SURNAME, GIVENNAME, GENDER)
--PRIMARY KEY (STUDENTID)

--SUBJECTOFFERING (SUBJCODE, YEAR, SEMESTER, FEE, STAFFID)
--PRIMARY KEY (SUBJCODE, YEAR, SEMESTER)
--FOREIGN KEY (SUBJCODE) REF SUBJECT
--FOREIGN KEY (STAFFID) REF TEACHER

--ENROLMENT (STUDENTID, YEAR, SEMESTER, SUBJCODE, DATE_ENROLLED, GRADE)
--PRIMARY KEY (STUDENTID, YEAR, SEMESTER, SUBJCODE) 
--FOREIGN KEY (STUDENTID, YEAR, SEMESTER, SUBJCODE) REF SUBJECTOFFERING 
--FOREIGN KEY (STUDENTID) REF STUDENT

