--MARINA PAJVANCIC
--103340660

--RELATIONAL SCHEMA

--SUBJECT(SUBJCODE, DESCRIPTION)
--PRIMARY KEY (SUBJCODE)

--TEACHER (STAFFID, SURNAME, GIVENNAME)
--PRIMARY KEY (STAFFID)

--STUDENT(STUDENTID, SURNAME, GIVENNAME, GENDER)
--PRIMARY KEY (STUDENTID)

--SUBJECTOFFERING (SUBJCODE, YEAR, SEMESTER, FEE, STAFFID)
--PRIMARY KEY (SUBJCODE, YEAR, SEMESTER)
--FOREIGN KEY (SUBJCODE) REF SUBJECT
--FOREIGN KEY (STAFFID) REF TEACHER

--ENROLMENT (STUDENTID, SUBJCODE, YEAR, SEMESTER, GRADE, DATE_ENROLLED,)
--PRIMARY KEY (STUDENTID, YEAR, SEMESTER, SUBJCODE) 
--FOREIGN KEY (STUDENTID, YEAR, SEMESTER, SUBJCODE) REF SUBJECTOFFERING 
--FOREIGN KEY (STUDENTID) REF STUDENT

CREATE TABLE SUBJECT
(
    SUBJCODE NVARCHAR(100),
    DESCRIPTION NVARCHAR(500),
    PRIMARY KEY (SUBJCODE)
);

CREATE TABLE TEACHER 
(STAFFID INT,
 SURNAME NVARCHAR(100) NOT NULL,
 GIVENNAME NVARCHAR(100) NOT NULL,
PRIMARY KEY (STAFFID),
CONSTRAINT CHK_TEACHER_STAFFID CHECK (LEN (STAFFID)= 8));

CREATE TABLE STUDENT
(STUDENTID NVARCHAR(10), 
SURNAME NVARCHAR(100) NOT NULL, 
GIVENNAME NVARCHAR(100) NOT NULL, 
GENDER NVARCHAR(100),
PRIMARY KEY (STUDENTID),
CONSTRAINT CHK_STUDENT_GENDER CHECK (GENDER IN ('M', 'F', 'I')));

CREATE TABLE SUBJECTOFFERING 
(SUBJCODE NVARCHAR(100),
YEAR INT, 
SEMESTER INT,
FEE MONEY not null,
STAFFID INT,
PRIMARY KEY (SUBJCODE,YEAR, SEMESTER),
FOREIGN KEY (SUBJCODE) REFERENCES SUBJECT,
FOREIGN KEY (STAFFID) REFERENCES TEACHER,
CONSTRAINT CHK_SUBJECTOFFERING_SEMESTER CHECK (SEMESTER IN (1,2)),
CONSTRAINT CHK_SUBJECTOFFERING_FEE CHECK (FEE > 0),
CONSTRAINT CHK_SUBJECTOFFERING_YEAR CHECK (LEN (YEAR) = 4),
);

CREATE TABLE ENROLMENT  
(STUDENTID NVARCHAR(10), 
SUBJCODE NVARCHAR(100), 
YEAR INT, 
SEMESTER INT, 
GRADE NVARCHAR(2),
DATE_ENROLLED DATE, 
PRIMARY KEY (STUDENTID, SUBJCODE, YEAR, SEMESTER), /*refereces the primary keys of tables STUDENT AND SUBJOFFERING*/
FOREIGN KEY (SUBJCODE,YEAR, SEMESTER) REFERENCES SUBJECTOFFERING, 
FOREIGN KEY (STUDENTID) REFERENCES STUDENT,
CONSTRAINT CHK_ENROLMENT_YEAR CHECK (LEN (YEAR) = 4),
CONSTRAINT CHK_ENROLMENT_SEMESTER CHECK (SEMESTER IN (1,2))
);

SELECT NAME FROM sys.objects
WHERE TYPE = 'U';

--task 2 completed

